<?php
/**
 * Constants required for API usage from the various sites
 *
 * PHP version 5
 *
 * @category  Final_Fantasy_XIV
 * @package   FfxivDataSet
 * @author    Aric Stewart <aricstewart@google.com>
 * @copyright 2019 Aric Stewart
 * @license   Apache License, Version 2.0
 * @link      <none>
 **/

$server = 'Coeurl';
$ffxivmbGuid = '';
$xivapiKey = '';

$DBHOST = "localhost";
$DBUSER = "ffxiv";
$DBNAME = "ffxiv_craft";
$DBPASS = "";
