version: "3.2"
services:
  php:
    build: './docker/php/'
    depends_on:
      - mysql
    networks:
      - backend
    volumes:
      - .:/var/www/html/
    environment:
        DBHOST: 'mysql:${DBPORT:-3306}'
        DBNAME: ${DBNAME}
        DBPASS: ${DBPASS}
        DBUSER: ${DBUSER}
        DBPORT: ${DBPORT:-3306}
        API_SERVER: "http://apache"
  composer:
    restart: 'no'
    image: "composer"
    command: install
    volumes:
      - .:/app
  apache:
    build: './docker/apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html/
  mysql:
    image: mysql:5.6.40
    container_name: ffxiv_mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: ${DBROOTPW}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_PASSWORD: ${DBPASS}
      MYSQL_USER: ${DBUSER}
      MYSQL_TCP_PORT: ${DBPORT:-3306}
    ports:
      - "${DBPORT:-3306}:${DBPORT:-3306}"
    expose:
      - ${DBPORT:-3306}
    volumes:
      - mysql:/var/lib/mysql
networks:
  frontend:
  backend:
volumes:
  mysql:
