name: Run PHPCS on pull requests

on: pull_request

jobs:
  phpcs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: rtCamp/action-phpcs-code-review@master
      env:
        GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      with:
        args: "WordPress"
