name: Run PHPCS on pull requests

on: pull_request

jobs:
  phpcs:

    runs-on: ubuntu-latest

    steps:
    - uses: Automattic/vip-go-ci@master
    - uses: actions/checkout@master
    - uses: AricStewart/action-phpcs-code-review@master
      env:
        GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      with:
        args: "WordPress"
